import { Briefcase, Diamond, Zap } from 'lucide-react'

export const countryCodes = [
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', iso: 'af' },
  { code: '+355', country: 'Albania', flag: '🇦🇱', iso: 'al' },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', iso: 'dz' },
  { code: '+376', country: 'Andorra', flag: '🇦🇩', iso: 'ad' },
  { code: '+244', country: 'Angola', flag: '🇦🇴', iso: 'ao' },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', iso: 'ar' },
  { code: '+374', country: 'Armenia', flag: '🇦🇲', iso: 'am' },
  { code: '+297', country: 'Aruba', flag: '🇦🇼', iso: 'aw' },
  { code: '+61', country: 'Australia', flag: '🇦🇺', iso: 'au' },
  { code: '+43', country: 'Austria', flag: '🇦🇹', iso: 'at' },
  { code: '+994', country: 'Azerbaijan', flag: '🇦🇿', iso: 'az' },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', iso: 'bh' },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', iso: 'bd' },
  { code: '+375', country: 'Belarus', flag: '🇧🇾', iso: 'by' },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', iso: 'be' },
  { code: '+501', country: 'Belize', flag: '🇧🇿', iso: 'bz' },
  { code: '+229', country: 'Benin', flag: '🇧🇯', iso: 'bj' },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', iso: 'bt' },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴', iso: 'bo' },
  { code: '+387', country: 'Bosnia and Herzegovina', flag: '🇧🇦', iso: 'ba' },
  { code: '+267', country: 'Botswana', flag: '🇧🇼', iso: 'bw' },
  { code: '+55', country: 'Brazil', flag: '🇧🇷', iso: 'br' },
  { code: '+673', country: 'Brunei Darussalam', flag: '🇧🇳', iso: 'bn' },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬', iso: 'bg' },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫', iso: 'bf' },
  { code: '+257', country: 'Burundi', flag: '🇧🇮', iso: 'bi' },
  { code: '+855', country: 'Cambodia', flag: '🇰🇭', iso: 'kh' },
  { code: '+237', country: 'Cameroon', flag: '🇨🇲', iso: 'cm' },
  { code: '+1', country: 'Canada', flag: '🇨🇦', iso: 'ca' },
  { code: '+238', country: 'Cape Verde', flag: '🇨🇻', iso: 'cv' },
  { code: '+236', country: 'Central African Republic', flag: '🇨🇫', iso: 'cf' },
  { code: '+235', country: 'Chad', flag: '🇹🇩', iso: 'td' },
  { code: '+56', country: 'Chile', flag: '🇨🇱', iso: 'cl' },
  { code: '+86', country: 'China', flag: '🇨🇳', iso: 'cn' },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', iso: 'co' },
  { code: '+269', country: 'Comoros', flag: '🇰🇲', iso: 'km' },
  { code: '+242', country: 'Congo', flag: '🇨🇬', iso: 'cg' },
  {
    code: '+243',
    country: 'Congo, The Democratic Republic of the Congo',
    flag: '🇨🇩',
    iso: 'cd',
  },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷', iso: 'cr' },
  { code: '+225', country: "Côte d'Ivoire", flag: '🇨🇮', iso: 'ci' },
  { code: '+385', country: 'Croatia', flag: '🇭🇷', iso: 'hr' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', iso: 'cu' },
  { code: '+357', country: 'Cyprus', flag: '🇨🇾', iso: 'cy' },
  { code: '+420', country: 'Czech Republic', flag: '🇨🇿', iso: 'cz' },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', iso: 'dk' },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯', iso: 'dj' },
  { code: '+1849', country: 'Dominican Republic', flag: '🇩🇴', iso: 'do' },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨', iso: 'ec' },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', iso: 'eg' },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻', iso: 'sv' },
  { code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶', iso: 'gq' },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷', iso: 'er' },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', iso: 'ee' },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', iso: 'et' },
  { code: '+679', country: 'Fiji', flag: '🇫🇯', iso: 'fj' },
  { code: '+358', country: 'Finland', flag: '🇫🇮', iso: 'fi' },
  { code: '+33', country: 'France', flag: '🇫🇷', iso: 'fr' },
  { code: '+594', country: 'French Guiana', flag: '🇬🇫', iso: 'gf' },
  { code: '+689', country: 'French Polynesia', flag: '🇵🇫', iso: 'pf' },
  { code: '+241', country: 'Gabon', flag: '🇬🇦', iso: 'ga' },
  { code: '+220', country: 'Gambia', flag: '🇬🇲', iso: 'gm' },
  { code: '+995', country: 'Georgia', flag: '🇬🇪', iso: 'ge' },
  { code: '+49', country: 'Germany', flag: '🇩🇪', iso: 'de' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', iso: 'gh' },
  { code: '+30', country: 'Greece', flag: '🇬🇷', iso: 'gr' },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹', iso: 'gt' },
  { code: '+224', country: 'Guinea', flag: '🇬🇳', iso: 'gn' },
  { code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼', iso: 'gw' },
  { code: '+592', country: 'Guyana', flag: '🇬🇾', iso: 'gy' },
  { code: '+509', country: 'Haiti', flag: '🇭🇹', iso: 'ht' },
  { code: '+504', country: 'Honduras', flag: '🇭🇳', iso: 'hn' },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰', iso: 'hk' },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', iso: 'hu' },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', iso: 'is' },
  { code: '+91', country: 'India', flag: '🇮🇳', iso: 'in' },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', iso: 'id' },
  { code: '+98', country: 'Iran', flag: '🇮🇷', iso: 'ir' },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', iso: 'iq' },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', iso: 'ie' },
  { code: '+972', country: 'Israel', flag: '🇮🇱', iso: 'il' },
  { code: '+39', country: 'Italy', flag: '🇮🇹', iso: 'it' },
  { code: '+1876', country: 'Jamaica', flag: '🇯🇲', iso: 'jm' },
  { code: '+81', country: 'Japan', flag: '🇯🇵', iso: 'jp' },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', iso: 'jo' },
  { code: '+7', country: 'Kazakhstan', flag: '🇰🇿', iso: 'kz' },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', iso: 'ke' },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮', iso: 'ki' },
  {
    code: '+850',
    country: "Korea, Democratic People's Republic of Korea",
    flag: '🇰🇵',
    iso: 'kp',
  },
  {
    code: '+82',
    country: 'Korea, Republic of South Korea',
    flag: '🇰🇷',
    iso: 'kr',
  },
  { code: '+383', country: 'Kosovo', flag: '🇽🇰', iso: 'xk' },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', iso: 'kw' },
  { code: '+996', country: 'Kyrgyzstan', flag: '🇰🇬', iso: 'kg' },
  { code: '+856', country: 'Laos', flag: '🇱🇦', iso: 'la' },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', iso: 'lv' },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', iso: 'lb' },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸', iso: 'ls' },
  { code: '+231', country: 'Liberia', flag: '🇱🇷', iso: 'lr' },
  { code: '+218', country: 'Libyan Arab Jamahiriya', flag: '🇱🇾', iso: 'ly' },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮', iso: 'li' },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', iso: 'lt' },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺', iso: 'lu' },
  { code: '+853', country: 'Macao', flag: '🇲🇴', iso: 'mo' },
  { code: '+389', country: 'Macedonia', flag: '🇲🇰', iso: 'mk' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬', iso: 'mg' },
  { code: '+265', country: 'Malawi', flag: '🇲🇼', iso: 'mw' },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', iso: 'my' },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', iso: 'mv' },
  { code: '+223', country: 'Mali', flag: '🇲🇱', iso: 'ml' },
  { code: '+356', country: 'Malta', flag: '🇲🇹', iso: 'mt' },
  { code: '+692', country: 'Marshall Islands', flag: '🇲🇭', iso: 'mh' },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷', iso: 'mr' },
  { code: '+230', country: 'Mauritius', flag: '🇲🇺', iso: 'mu' },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', iso: 'mx' },
  { code: '+373', country: 'Moldova', flag: '🇲🇩', iso: 'md' },
  { code: '+377', country: 'Monaco', flag: '🇲🇨', iso: 'mc' },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', iso: 'mn' },
  { code: '+382', country: 'Montenegro', flag: '🇲🇪', iso: 'me' },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', iso: 'ma' },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿', iso: 'mz' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', iso: 'mm' },
  { code: '+264', country: 'Namibia', flag: '🇳🇦', iso: 'na' },
  { code: '+674', country: 'Nauru', flag: '🇳🇷', iso: 'nr' },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', iso: 'np' },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', iso: 'nl' },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', iso: 'nz' },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮', iso: 'ni' },
  { code: '+227', country: 'Niger', flag: '🇳🇪', iso: 'ne' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', iso: 'ng' },
  { code: '+47', country: 'Norway', flag: '🇳🇴', iso: 'no' },
  { code: '+968', country: 'Oman', flag: '🇴🇲', iso: 'om' },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', iso: 'pk' },
  { code: '+680', country: 'Palau', flag: '🇵🇼', iso: 'pw' },
  { code: '+507', country: 'Panama', flag: '🇵🇦', iso: 'pa' },
  { code: '+675', country: 'Papua New Guinea', flag: '🇵🇬', iso: 'pg' },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾', iso: 'py' },
  { code: '+51', country: 'Peru', flag: '🇵🇪', iso: 'pe' },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', iso: 'ph' },
  { code: '+48', country: 'Poland', flag: '🇵🇱', iso: 'pl' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹', iso: 'pt' },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', iso: 'qa' },
  { code: '+40', country: 'Romania', flag: '🇷🇴', iso: 'ro' },
  { code: '+7', country: 'Russia', flag: '🇷🇺', iso: 'ru' },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼', iso: 'rw' },
  { code: '+1869', country: 'Saint Kitts and Nevis', flag: '🇰🇳', iso: 'kn' },
  { code: '+1758', country: 'Saint Lucia', flag: '🇱🇨', iso: 'lc' },
  {
    code: '+1784',
    country: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    iso: 'vc',
  },
  { code: '+685', country: 'Samoa', flag: '🇼🇸', iso: 'ws' },
  { code: '+378', country: 'San Marino', flag: '🇸🇲', iso: 'sm' },
  { code: '+239', country: 'Sao Tome and Principe', flag: '🇸🇹', iso: 'st' },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', iso: 'sa' },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', iso: 'sn' },
  { code: '+381', country: 'Serbia', flag: '🇷🇸', iso: 'rs' },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨', iso: 'sc' },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱', iso: 'sl' },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', iso: 'sg' },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', iso: 'sk' },
  { code: '+386', country: 'Slovenia', flag: '🇸🇮', iso: 'si' },
  { code: '+677', country: 'Solomon Islands', flag: '🇸🇧', iso: 'sb' },
  { code: '+252', country: 'Somalia', flag: '🇸🇴', iso: 'so' },
  { code: '+27', country: 'South Africa', flag: '🇿🇦', iso: 'za' },
  { code: '+211', country: 'South Sudan', flag: '🇸🇸', iso: 'ss' },
  { code: '+34', country: 'Spain', flag: '🇪🇸', iso: 'es' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', iso: 'lk' },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', iso: 'sd' },
  { code: '+597', country: 'Suriname', flag: '🇸🇷', iso: 'sr' },
  { code: '+268', country: 'Swaziland', flag: '🇸🇿', iso: 'sz' },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', iso: 'se' },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', iso: 'ch' },
  { code: '+963', country: 'Syrian Arab Republic', flag: '🇸🇾', iso: 'sy' },
  { code: '+886', country: 'Taiwan', flag: '🇹🇼', iso: 'tw' },
  { code: '+992', country: 'Tajikistan', flag: '🇹🇯', iso: 'tj' },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', iso: 'tz' },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', iso: 'th' },
  { code: '+670', country: 'Timor-Leste', flag: '🇹🇱', iso: 'tl' },
  { code: '+228', country: 'Togo', flag: '🇹🇬', iso: 'tg' },
  { code: '+676', country: 'Tonga', flag: '🇹🇴', iso: 'to' },
  { code: '+1868', country: 'Trinidad and Tobago', flag: '🇹🇹', iso: 'tt' },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', iso: 'tn' },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', iso: 'tr' },
  { code: '+993', country: 'Turkmenistan', flag: '🇹🇲', iso: 'tm' },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻', iso: 'tv' },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', iso: 'ug' },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', iso: 'ua' },
  { code: '+971', country: 'United Arab Emirates', flag: '🇦🇪', iso: 'ae' },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', iso: 'gb' },
  { code: '+1', country: 'United States', flag: '🇺🇸', iso: 'us' },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾', iso: 'uy' },
  { code: '+998', country: 'Uzbekistan', flag: '🇺🇿', iso: 'uz' },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺', iso: 'vu' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', iso: 've' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', iso: 'vn' },
  { code: '+967', country: 'Yemen', flag: '🇾🇪', iso: 'ye' },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', iso: 'zm' },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', iso: 'zw' },
]

export const plans = [
  {
    id: 'starter',
    title: 'Starter',
    price: 149.99,
    originalPrice: 199.99,
    icon: Zap,
  },
  {
    id: 'professional',
    title: 'Professional',
    price: 349.99,
    originalPrice: 499.99,
    icon: Briefcase,
  },
  {
    id: 'high-conversion',
    title: 'High Conversion',
    price: 799.99,
    originalPrice: 1299.99,
    icon: Diamond,
  },
]

export const paymentMethods = [
  { id: 'paypal', title: 'PayPal', icon: '/assets/icons/paypal.svg' },
  { id: 'wise', title: 'Wise', icon: '/assets/icons/wise.svg' },
  { id: 'stripe', title: 'Stripe', icon: '/assets/icons/stripe.svg' },
]
